"""Predictive Guardian — Pydantic schemas."""
from __future__ import annotations

from datetime import datetime
from typing import Any

from pydantic import BaseModel, Field


class ForecastPoint(BaseModel):
    """A single forecasted data point."""

    period: int  # 1 = next period, 2 = 2 periods ahead, etc.
    predicted_value: float
    lower_bound: float | None = None
    upper_bound: float | None = None


class MetricForecast(BaseModel):
    """Forecast for a single metric."""

    label: str
    current_value: float
    trend: str  # "improving", "declining", "stable"
    slope: float
    next_prediction: float
    predictions: list[ForecastPoint] = Field(default_factory=list)
    confidence_interval: tuple[float, float] | None = None
    volatility: float = 0.0
    moving_average: float | None = None
    days_to_critical: int | None = None
    critical_threshold: float | None = None


class PredictiveAlert(BaseModel):
    """Alert generated by the predictive guardian."""

    should_alert: bool
    metric: str = ""
    severity: str = "info"  # info, warning, critical
    current_value: float = 0.0
    predicted_value: float = 0.0
    threshold: float | None = None
    days_until_crossing: int | None = None
    description: str = ""
    confidence: str = "medium"  # high, medium, low


class RunwayForecast(BaseModel):
    """Runway depletion forecast."""

    base_runway_days: int
    adjusted_runway_days: int
    depletion_date_description: str = ""
    confidence: str = "medium"
    burn_trend: str = "stable"  # accelerating, stable, declining
    mrr_trend: str = "stable"


class ChurnForecast(BaseModel):
    """Churn acceleration forecast."""

    accelerating: bool = False
    overall_slope: float = 0.0
    recent_slope: float = 0.0
    risk_level: str = "low"
    description: str = ""


class PredictiveSnapshot(BaseModel):
    """Complete predictive state for a tenant."""

    tenant_id: str
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    forecasts: list[MetricForecast] = Field(default_factory=list)
    alerts: list[PredictiveAlert] = Field(default_factory=list)
    runway: RunwayForecast | None = None
    churn: ChurnForecast | None = None
    has_alerts: bool = False
